import { DataTypes, Model, ModelAttributes } from "sequelize";
import { accountModelName } from "./account";

enum BoothStatus {
  OPEN = "open",
  PAUSE = "pause",
  CLOSE = "close",
  PREPARE = "prepare",
}

interface IBooth {
  id: number;
  ownerId: number;  // Foreign key to Account.id
  name: string;
  description?: string;
  location: string;
  currencySymbol: string;
  status: BoothStatus;
  statusReason?: string;
  statusPublishContent?: boolean;

  // Will be autogenerated by Sequelize
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}

type BoothCreationAttributes = Omit<IBooth, "id" | "description" | "status" | "statusReason" | "statusPublishContent">
                               & Partial<Pick<IBooth, "description" | "status" | "statusReason" | "statusPublishContent">>;
export default class Booth extends Model<IBooth, BoothCreationAttributes> implements IBooth {
  declare id: number;
  declare ownerId: number;
  declare name: string;
  declare description?: string;
  declare location: string;
  declare currencySymbol: string;
  declare status: BoothStatus;
  declare statusReason?: string;
  declare statusPublishContent?: boolean;
}

const boothModelName = "Booth";
const boothModelAttrib: ModelAttributes<Booth> = {
  id: {
    type: DataTypes.INTEGER.UNSIGNED,
    unique: true,
    primaryKey: true,
    autoIncrement: true,
    allowNull: false,
  },
  ownerId: {
    type: DataTypes.INTEGER.UNSIGNED,
    allowNull: false,
    references: {
      model: accountModelName,
      key: "id",
    },
  },
  name: {
    type: DataTypes.STRING(256),
    allowNull: false,
  },
  description: {
    type: DataTypes.STRING(1024),
    allowNull: true,
    defaultValue: null,
  },
  location: {
    type: DataTypes.STRING(512),
    allowNull: false,
  },
  currencySymbol: {
    type: DataTypes.STRING(8),
    allowNull: false,
    defaultValue: "₩",
  },
  status: {
    type: DataTypes.ENUM(...Object.values(BoothStatus)),
    allowNull: false,
    defaultValue: BoothStatus.PREPARE,
  },
  statusReason: {
    type: DataTypes.STRING(1024),
    allowNull: true,
    defaultValue: null,
  },
  statusPublishContent: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false,
  },
};

export { IBooth, BoothStatus, BoothCreationAttributes, boothModelName, boothModelAttrib };
