import { ModelAttributes, Model, DataTypes } from "sequelize";
import { goodsModelName } from "./goods";

interface IGoodsCategory {
  id: number;
  boothId: number;  // Foreign key to Booth.id
  name: string;

  // Will be autogenerated by Sequelize
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}

type GoodsCategoryCreationAttributes = Omit<IGoodsCategory, "id">;
export default class GoodsCategory extends Model<IGoodsCategory, GoodsCategoryCreationAttributes> implements IGoodsCategory {
  declare id: number;
  declare boothId: number;
  declare name: string;
}

const goodsCategoryModelName = "GoodsCategory";
const goodsCategoryModelAttrib: ModelAttributes<GoodsCategory> = {
  id: {
    type: DataTypes.INTEGER.UNSIGNED,
    unique: true,
    primaryKey: true,
    autoIncrement: true,
    allowNull: false,
  },
  boothId: {
    type: DataTypes.INTEGER.UNSIGNED,
    allowNull: false,
    references: {
      model: goodsModelName,
      key: "id",
    },
  },
  name: {
    type: DataTypes.STRING(256),
    allowNull: false,
  },
};

export { IGoodsCategory, GoodsCategoryCreationAttributes, goodsCategoryModelName, goodsCategoryModelAttrib };
