name: myboothmanager

networks:
  default:
    name: myboothmanager
    external: true

services:
  admin:
    build:
      context: .
      dockerfile: ./projects/Admin/Containerfile
      args:
        GIT_HASH: ${GIT_COMMIT_HASH}
        API_SERVER_URL: "http://localhost:31111"
        PUBLIC_APP_URL: "http://localhost:31113"
        BASE_PATH: "/admin"
    ports:
      - "31112:31112"
    depends_on:
      - backend
    restart: unless-stopped

  public:
    build:
      context: .
      dockerfile: ./projects/Public/Containerfile
      args:
        GIT_HASH: ${GIT_COMMIT_HASH}
    environment:
      NITRO_PORT: 31113
      GIT_HASH: ${GIT_COMMIT_HASH}
      NUXT_PUBLIC_API_SERVER_URL: "http://localhost:31111"
      NUXT_PUBLIC_API_SERVER_UPLOADS_PATH: "uploads"
      NUXT_APP_BASE_PATH: "/"
    ports:
      - "31113:31113"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./projects/Backend/Containerfile
    volumes:
      - mbm-uploads:/app/uploads
    ports:
      - "31111:31111"
    environment:
      TRUST_LOCALHOST_PROXY: true
      API_SERVER_PORT: 31111
      SUPERADMIN_ID: admin
      SUPERADMIN_PASS: should1be2changed!
      SUPERADMIN_DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/...
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: myboothmanager
      SEQUELIZE_TIMEZONE: +09:00
      JWT_SECRET: som_myboothmanager_ni
      COOKIE_SECRET: in_myboothmanager_mos
      FRONTEND_ADMIN_URL: "http://localhost:31112"
      FRONTEND_PUBLIC_URL: "http://localhost:31113"
    restart: unless-stopped

volumes:
  mbm-uploads:
