### BUILD STAGE ###
FROM node:lts-alpine as build

# Build arguments
ARG GIT_HASH
ARG API_SERVER_URL=http://localhost:31111
ARG PUBLIC_APP_URL=http://localhost:31113
ARG BASE_PATH=/admin
ENV GIT_HASH=${GIT_HASH}
ENV VITE_MBM_API_SERVER_URL=${API_SERVER_URL}
ENV VITE_MBM_PUBLIC_URL=${PUBLIC_APP_URL}
ENV VITE_BASE_PATH=${BASE_PATH}

# Copy files
WORKDIR /build
COPY packages/      packages/
COPY projects/Admin projects/Admin

# Build common package
WORKDIR /build/packages/Common
# Workaround
RUN rm .containerignore
RUN yarn set version berry
RUN yarn install
RUN yarn build

# Build admin frontend
WORKDIR /build/projects/Admin
RUN yarn set version berry
RUN yarn install
RUN yarn build

### PRODUCTION STAGE ###
FROM node:lts-alpine as production

# Copy files
WORKDIR /app
COPY --from=build /build/projects/Admin/dist .

# Expose port
EXPOSE 31112

# Start server
RUN npm install -g http-server
ENTRYPOINT ["npx", "http-server", "--proxy", "http://localhost:31112?", "--port", "31112"]
