### BUILD STAGE ###
FROM node:lts-alpine as build
RUN corepack enable pnpm

# Build arguments
ARG GIT_HASH
ARG API_SERVER_URL=http://localhost:31111
ARG PUBLIC_APP_URL=http://localhost:31113
ARG BASE_PATH=/admin
ENV GIT_HASH=${GIT_HASH}
ENV VITE_MBM_API_SERVER_URL=${API_SERVER_URL}
ENV VITE_MBM_PUBLIC_URL=${PUBLIC_APP_URL}
ENV VITE_ADMIN_BASE_PATH=${BASE_PATH}

# Copy files
WORKDIR /build
COPY package.json pnpm-*.yaml .
COPY packages/      packages/
COPY projects/Admin projects/Admin

# Build
# RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
#     pnpm install --frozen-lockfile
RUN pnpm install --frozen-lockfile
RUN pnpm common:build && pnpm admin build

# No need to deploy; all build artifacts are in dist folder as static files
# RUN pnpm deploy --filter @myboothmanager/admin --prod /prod/admin


### PRODUCTION STAGE ###
FROM ghcr.io/static-web-server/static-web-server:latest as production

# Copy files
WORKDIR /app
COPY --from=build /build/projects/Admin/dist .

# static-web-server environment
ENV SERVER_PORT=31112
ENV SERVER_ROOT=/app
ENV SERVER_LOG_REMOTE_ADDRESS=true
ENV SERVER_LOG_FORWARDED_FOR=true
ENV SERVER_FALLBACK_PAGE=index.html
ENV SERVER_DIRECTORY_LISTING=false

# Expose port
EXPOSE 31112

# static-seb-server is automatically started
