### BUILD STAGE ###
FROM node:lts-alpine as build

# Build arguments
ARG GIT_HASH
ARG API_SERVER_URL=http://localhost:31111
ARG BASE_PATH=/
ENV GIT_HASH=${GIT_HASH}
ENV VITE_MBM_API_SERVER_URL=${API_SERVER_URL}
ENV VITE_BASE_PATH=${BASE_PATH}

# Copy files
WORKDIR /build
COPY package.json .
COPY packages/      packages/
COPY projects/Public projects/Public

# Build setup
RUN yarn set version berry
RUN yarn install

# Build common package
RUN yarn common build

# Build common UI package
RUN yarn install
RUN yarn install && yarn commonui build

# Build public frontend
RUN yarn install && yarn public build

### PRODUCTION STAGE ###
FROM node:lts-alpine as production

# Copy files
WORKDIR /app
COPY --from=build /build/projects/Public/dist .

# Expose port
EXPOSE 31113

# Start server
RUN npm install -g http-server
ENTRYPOINT ["npx", "http-server", "--proxy", "http://localhost:31113?", "--port", "31113"]
