import { OmitSequelizeInternals } from "src/utils/internals";

interface IAccount {
  id: number;
  name: string;
  loginId: string;
  loginPassHash: string;
  loginCount: number;
  lastLoginAt: Date;

  // Will be autogenerated by Sequelize
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}

type AccountCreateRequestKey = "name" | "loginId" | "loginPassHash";
type IAccountCreateRequest = Pick<IAccount, AccountCreateRequestKey>;

type IAccountResponse = OmitSequelizeInternals<IAccount>;

export { IAccount, AccountCreateRequestKey, IAccountCreateRequest, IAccountResponse };
