import { OmitSequelizeInternals } from "src/utils/internals";

export interface IAccount {
  id: number;
  name: string;
  loginId: string;
  loginPassHash: string;
  loginCount: number;
  lastLoginAt: Date;

  // Will be autogenerated by Sequelize
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}

export type AccountCreateRequestKey = "name" | "loginId" | "loginPassHash";
export type IAccountCreateRequest = Pick<IAccount, AccountCreateRequestKey>;

export type IAccountResponse = OmitSequelizeInternals<IAccount>;
