import { OmitSequelizeInternals } from "src/utils/internals";

export enum BoothStatus {
  OPEN = "open",
  PAUSE = "pause",
  CLOSE = "close",
  PREPARE = "prepare",
}

export interface IBooth {
  id: number;
  ownerId: number;  // Foreign key to Account.id
  name: string;
  description?: string;
  location: string;
  currencySymbol: string;
  status: BoothStatus;
  statusReason?: string;
  statusPublishContent?: boolean;

  // Will be autogenerated by Sequelize
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}

export type BoothCreateRequestKey = "name" | "description" | "location" | "currencySymbol";
export type IBoothCreateRequest = Pick<IBooth, BoothCreateRequestKey>;

export type IBoothResponse = OmitSequelizeInternals<IBooth>;
