enum BoothStatus {
  OPEN = "open",
  PAUSE = "pause",
  CLOSE = "close",
  PREPARE = "prepare",
}

interface IBooth {
  id: number;
  ownerId: number;  // Foreign key to Account.id
  name: string;
  description?: string;
  location: string;
  currencySymbol: string;
  status: BoothStatus;
  statusReason?: string;
  statusPublishContent?: boolean;

  // Will be autogenerated by Sequelize
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}

export { IBooth, BoothStatus };
