import { OmitSequelizeInternals } from "src/utils/internals";

enum GoodsStatus {
  ON_SALE ="on_sale",
  PAUSE = "pause",
  SOLD_OUT = "sold_out",
}

interface IGoods {
  id: number;
  boothId: number;  // Foreign key to Booth.id
  categoryId?: number;  // Foreign key to GoodsCategory.id
  name: string;
  description?: string;
  status: GoodsStatus;
  statusReason?: string;
  price: number;
  stockInitial: number;
  stockRemaining: number;

  // Will be autogenerated by Sequelize
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}

type GoodsCreateRequestKey = "boothId" | "categoryId" | "name" | "description" | "price" | "stockInitial" | "stockRemaining";
type IGoodsCreateRequest = Pick<IGoods, GoodsCreateRequestKey>;

type IGoodsResponse = OmitSequelizeInternals<IGoods>;

export { IGoods, GoodsStatus, GoodsCreateRequestKey, IGoodsCreateRequest, IGoodsResponse };
