import { OmitSequelizeInternals } from "src/utils/internals";

interface IGoodsSaleHistory {
  id: number;
  goodsId: number;  // Foreign key to Goods.id
  price: number;
  stockChanges: number;
  timestamp: Date;

  // Will be autogenerated by Sequelize
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}

type GoodsSaleHistoryCreateRequestKey = "goodsId" | "price" | "stockChanges" | "timestamp";
type IGoodsSaleHistoryCreateRequest = Pick<IGoodsSaleHistory, GoodsSaleHistoryCreateRequestKey>;

type IGoodsSaleHistoryResponse = OmitSequelizeInternals<IGoodsSaleHistory>;

export { IGoodsSaleHistory, GoodsSaleHistoryCreateRequestKey, IGoodsSaleHistoryCreateRequest, IGoodsSaleHistoryResponse };
