enum GoodsStatus {
  ON_SALE ="on_sale",
  PAUSE = "pause",
  SOLD_OUT = "sold_out",
}

interface IGoods {
  id: number;
  boothId: number;  // Foreign key to Booth.id
  categoryId?: number;  // Foreign key to GoodsCategory.id
  name: string;
  description?: string;
  status: GoodsStatus;
  statusReason?: string;
  price: number;
  stockInitial: number;
  stockRemaining: number;

  // Will be autogenerated by Sequelize
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}


export { IGoods, GoodsStatus };
