import { OmitSequelizeInternals } from "src/utils/internals";

interface IGoodsCategory {
  id: number;
  boothId: number;  // Foreign key to Booth.id
  name: string;

  // Will be autogenerated by Sequelize
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}

type GoodsCategoryCreateRequestKey = "boothId" | "name";
type IGoodsCategoryCreateRequest = Pick<IGoodsCategory, GoodsCategoryCreateRequestKey>;

type IGoodsCategoryResponse = OmitSequelizeInternals<IGoodsCategory>;

export { IGoodsCategory, GoodsCategoryCreateRequestKey, IGoodsCategoryCreateRequest, IGoodsCategoryResponse };
