interface IGoodsSaleHistory {
  id: number;
  goodsId: number;  // Foreign key to Goods.id
  price: number;
  stockChanges: number;
  timestamp: Date;

  // Will be autogenerated by Sequelize
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}

export { IGoodsSaleHistory };
