interface IGoodsCategory {
  id: number;
  boothId: number;  // Foreign key to Booth.id
  name: string;

  // Will be autogenerated by Sequelize
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}

export { IGoodsCategory };
