### BASE ###
FROM node:lts-alpine as base

### BUILD STAGE ###
FROM base as build
RUN corepack enable pnpm

# Copy files
WORKDIR /build
COPY package.json pnpm-*.yaml .
COPY packages/Common  packages/Common
COPY projects/Backend projects/Backend

# Build
# RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
#     pnpm install --frozen-lockfile
RUN pnpm install --frozen-lockfile
RUN pnpm common build && pnpm backend build

# Deploy
RUN pnpm deploy --filter @myboothmanager/backend --prod /prod/backend


### PRODUCTION STAGE ###
FROM base as production
RUN corepack enable pnpm

# Copy files
WORKDIR /app
COPY --from=build /prod/backend .

# DB migration notice
RUN printf "\n\n  *** DB MIGRATION WILL BE EXECUTED DURING CONTAINER STARTUP ***  \n"; \
  printf " - You can undo migration manually by running 'yarn workspace @myboothmanager/backend migrate:prod down' if there's any issue. \n"; \
  printf " - After undoing migration, Use 'start:prod:no-migration' package.json script to run production without DB migration. \n\n\n";

# Expose port
EXPOSE 31111

# Start server
ENTRYPOINT ["/bin/sh", "-c", "pnpm migrate:prod && pnpm start:prod"]
