### BUILD STAGE ###
FROM node:lts-alpine as build

# Copy files
WORKDIR /build
COPY packages/        packages/
COPY projects/Backend projects/Backend

# Build common package
WORKDIR /build/packages/Common
# Workaround
RUN rm .containerignore
RUN yarn set version berry
RUN yarn install
RUN yarn build

# Build backend
WORKDIR /build/projects/Backend
RUN yarn set version berry
RUN yarn install
RUN yarn build

### PRODUCTION STAGE ###
FROM node:lts-alpine as production

# Copy files
WORKDIR /app
COPY              ./package.json                       ./package.json
COPY --from=build /build/packages/Common/dist          packages/Common/dist
COPY --from=build /build/packages/Common/package.json  packages/Common/package.json
COPY --from=build /build/projects/Backend/dist         projects/Backend/dist
COPY --from=build /build/projects/Backend/package.json projects/Backend/package.json

# Using Yarn Berry
RUN yarn set version berry

# Install production dependencies
RUN yarn workspaces focus @myboothmanager/backend --production

# DB migration notice
RUN printf "\n\n  *** DB MIGRATION WILL BE EXECUTED DURING CONTAINER STARTUP ***  \n"; \
  printf " - You can undo migration manually by running 'yarn workspace @myboothmanager/backend migrate:prod down' if there's any issue. \n"; \
  printf " - After undoing migration, Use 'start:prod:no-migration' package.json script to run production without DB migration. \n\n\n";

# Expose port
EXPOSE 31111

# Start server
ENTRYPOINT ["yarn", "workspace", "@myboothmanager/backend", "start:prod"]
